export const athleticKits = [
  {
    _id: 1,
    typeId: "1",
    name: "Форма легкоатлетическая мужская",
    image: [
      "/img/tshirt/tshirt-11.png",
      "/img/tshirt/tshirt-12.png",
      "/img/tshirt/tshirt-13.png",
    ],
    price: 15000,
    article: "Б-10",
    category: "мужская",
  },
  {
    _id: 2,
    type: "1",
    name: "Майка легкоатлетическая женская",
    image: [
      "/img/tshirt/tshirt-21.png",
      "/img/tshirt/tshirt-1.png",
      "/img/tshirt/tshirt-2.png",
    ],
    price: 15000,
    article: "ИД-10",
    category: "женская",
  },
  {
    _id: 3,
    type: "1",
    name: "Майка легкоатлетическая мужская",
    image: ["/img/tshirt/tshirt-31.png", "/img/tshirt/tshirt-32.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 4,
    type: "1",
    name: "Майка легкоатлетическая мужская",
    image: ["/img/tshirt/tshirt-41.png", "/img/tshirt/tshirt-51.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 5,
    type: "1",
    name: "Майка легкоатлетическая мужская",
    image: ["/img/tshirt/tshirt-61.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
];
