import { v4 as uuidv4 } from "uuid";

export const hockeyPlayTshirtKits = [
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-1.png",
      "/img/hockey/tshirts/h-tshirt-2.png",
      "/img/hockey/tshirts/h-tshirt-3.png",
    ],
    price: 13000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/1.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка вратаря",
    image: ["/img/typesport/playtshirt/1b.png"],
    price: 20000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка вратаря",
    image: ["/img/typesport/playtshirt/2b.png"],
    price: 20000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/2.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/3.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-4.png",
      "/img/hockey/tshirts/h-tshirt-7.png",
      "/img/hockey/tshirts/h-tshirt-8.png",
    ],
    price: 13000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-9.png",
      "/img/hockey/tshirts/h-tshirt-10.png",
      "/img/hockey/tshirts/h-tshirt-11.png",
    ],
    price: 13000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-12.png",
      "/img/hockey/tshirts/h-tshirt-13.png",
      "/img/hockey/tshirts/h-tshirt-14.png",
    ],
    price: 13000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-15.png",
      "/img/hockey/tshirts/h-tshirt-16.png",
      "/img/hockey/tshirts/h-tshirt-19.png",
    ],
    price: 15000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-21.png",
      "/img/hockey/tshirts/h-tshirt-25.png",
      "/img/hockey/tshirts/h-tshirt-26.png",
    ],
    price: 15000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-27.png",
      "/img/hockey/tshirts/h-tshirt-28.png",
      "/img/hockey/tshirts/h-tshirt-38.png",
    ],
    price: 15000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-40.png",
      "/img/hockey/tshirts/h-tshirt-41.png",
      "/img/hockey/tshirts/h-tshirt-44.png",
    ],
    price: 15000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-45.png",
      "/img/hockey/tshirts/h-tshirt-46.png",
      "/img/hockey/tshirts/h-tshirt-47.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-48.png",
      "/img/hockey/tshirts/h-tshirt-49.png",
      "/img/hockey/tshirts/h-tshirt-50.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-51.png",
      "/img/hockey/tshirts/h-tshirt-52.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-53.png",
      "/img/hockey/tshirts/h-tshirt-54.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/IMG-20230707-WA0022.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0032.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0034.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0036.jpg",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/IMG-20230707-WA0023.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0037.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0030.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0035.jpg",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/IMG-20230707-WA0028.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0024.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0025.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0029.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0033.jpg",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },

  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/IMG-20230707-WA0026.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0027.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0031.jpg",
      "/img/typesport/playtshirt/IMG-20230707-WA0033.jpg",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: ["/img/typesport/playtshirt/хсвитер38.png"],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: ["/img/typesport/playtshirt/хсвитер41.png"],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/хсвитер39.png",
      "/img/typesport/playtshirt/хсвитер40.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/хсвитер44.png",
      "/img/typesport/playtshirt/хсвитер45.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: ["/img/typesport/playtshirt/хсвитер42.png"],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },

  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: ["/img/typesport/playtshirt/хсвитер43.png"],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка. Сублимационная печать",
    image: [
      "/img/typesport/playtshirt/хсвитер46.png",
      "/img/typesport/playtshirt/хсвитер47.png",
    ],
    price: 19000,
    article: "Х-11",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/4.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/5.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/6.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка игровая с гамашами. Сублимационная печать ",
    image: ["/img/typesport/playtshirt/7.png"],
    price: 25000,
    article: "Х-10",
    category: "мужская",
  },
  {
    _id: uuidv4("sila-"),
    type: "h-1",
    name: "Хоккейная майка вратаря",
    image: ["/img/typesport/playtshirt/3b.png"],
    price: 20000,
    article: "Х-10",
    category: "мужская",
  },
];
