export const hockeyPlayTshirtKits = [
  {
    _id: 1,
    typeId: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-1.png",
      "/img/hockey/tshirts/h-tshirt-2.png",
      "/img/hockey/tshirts/h-tshirt-3.png",
    ],
    price: 15000,
    article: "Б-10",
    category: "мужская",
  },
  {
    _id: 2,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-4.png",
      "/img/hockey/tshirts/h-tshirt-7.png",
      "/img/hockey/tshirts/h-tshirt-8.png",
    ],
    price: 15000,
    article: "ИД-10",
    category: "мужская",
  },
  {
    _id: 3,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-9.png",
      "/img/hockey/tshirts/h-tshirt-10.png",
      "/img/hockey/tshirts/h-tshirt-11.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 4,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-12.png",
      "/img/hockey/tshirts/h-tshirt-13.png",
      "/img/hockey/tshirts/h-tshirt-14.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 5,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-15.png",
      "/img/hockey/tshirts/h-tshirt-16.png",
      "/img/hockey/tshirts/h-tshirt-19.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 6,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-21.png",
      "/img/hockey/tshirts/h-tshirt-25.png",
      "/img/hockey/tshirts/h-tshirt-26.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 7,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-27.png",
      "/img/hockey/tshirts/h-tshirt-28.png",
      "/img/hockey/tshirts/h-tshirt-38.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 8,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-40.png",
      "/img/hockey/tshirts/h-tshirt-41.png",
      "/img/hockey/tshirts/h-tshirt-44.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 9,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-45.png",
      "/img/hockey/tshirts/h-tshirt-46.png",
      "/img/hockey/tshirts/h-tshirt-47.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 10,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-48.png",
      "/img/hockey/tshirts/h-tshirt-49.png",
      "/img/hockey/tshirts/h-tshirt-50.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 11,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-51.png",
      "/img/hockey/tshirts/h-tshirt-52.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 12,
    type: "1",
    name: "Хоккейная майка на заказ",
    image: [
      "/img/hockey/tshirts/h-tshirt-53.png",
      "/img/hockey/tshirts/h-tshirt-54.png",
    ],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
];
