export const clothesTshirtPeKits = [
  {
    _id: 1,
    typeId: "1",
    name: "Футболки п/э",
    image: ["/img/clothes-tshirt/tshirt-1.png"],
    price: 15000,
    article: "Б-10",
    category: "мужская",
  },
  {
    _id: 2,
    type: "1",
    name: "Футболка с сублимационным нанесением",
    image: ["/img/clothes-tshirt/tshirt-10.png"],
    price: 15000,
    article: "ИД-10",
    category: "женская",
  },
  {
    _id: 3,
    type: "1",
    name: "Футболка с нанесением",
    image: ["/img/clothes-tshirt/tshirt-20.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 4,
    type: "1",
    name: "Футболка с нанесением",
    image: ["/img/clothes-tshirt/tshirt-30.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 5,
    type: "1",
    name: "Футболка с нанесением",
    image: ["/img/clothes-tshirt/tshirt-40.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 6,
    type: "1",
    name: "Футболка с нанесением",
    image: ["/img/clothes-tshirt/tshirt-50.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
];
