import { v4 as uuidv4 } from "uuid";

export const footballWomenKits = [
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-100.png"],
    price: 15000,
    article: "Б-10",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-210.png", "/img/football/complect-211.png"],
    price: 15000,
    article: "ИД-10",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-120.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-130.png", "/img/football/complect-131.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-10.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-150.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-160.png", "/img/football/complect-161.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-30.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-180.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-190.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футбольная форма",
    image: ["/img/football/complect-210.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футболка",
    image: ["/img/football/tshirt-1.png", "/img/football/tshirt-2.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: uuidv4("sila-"),
    type: "f-2",
    name: "Футболка",
    image: ["/img/football/short-1.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
];
