export const footballWomenKits = [
  {
    _id: 1,
    typeId: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-100.png"],
    price: 15000,
    article: "Б-10",
    category: "женская",
  },
  {
    _id: 2,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-210.png", "/img/football/complect-211.png"],
    price: 15000,
    article: "ИД-10",
    category: "женская",
  },
  {
    _id: 3,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-120.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 4,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-130.png", "/img/football/complect-131.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 5,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-10.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 6,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-150.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 7,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-160.png", "/img/football/complect-161.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 8,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-30.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 9,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-180.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 10,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-190.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 11,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-210.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 12,
    type: "1",
    name: "Футболка",
    image: ["/img/football/tshirt-1.png", "/img/football/tshirt-2.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
  {
    _id: 13,
    type: "1",
    name: "Футболка",
    image: ["/img/football/short-1.png"],
    price: 15000,
    article: "ИД-11",
    category: "женская",
  },
];
