export const footballManKits = [
  {
    _id: 1,
    typeId: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-1.png"],
    price: 15000,
    article: "Б-10",
    category: "мужская",
  },
  {
    _id: 2,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-210.png", "/img/football/complect-211.png"],
    price: 15000,
    article: "ИД-10",
    category: "мужская",
  },
  {
    _id: 3,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-10.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 4,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-20.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 5,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-30.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 6,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-40.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 7,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-50.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 8,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-60.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 9,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-70.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 10,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-80.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 11,
    type: "1",
    name: "Футбольная форма",
    image: ["/img/football/complect-90.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 12,
    type: "1",
    name: "Футболка",
    image: ["/img/football/tshirt-1.png", "/img/football/tshirt-2.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 13,
    type: "1",
    name: "Футболка",
    image: ["/img/football/short-1.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
];
