export const voleyballManKits = [
  {
    _id: 1,
    typeId: "1",
    name: "Волейбольная форма",
    image: ["/img/volleyball/complect-1.png"],
    price: 15000,
    article: "Б-10",
    category: "мужская",
  },
  {
    _id: 2,
    type: "2",
    name: "Волейбольная форма",
    image: ["/img/volleyball/complect-10.png"],
    price: 15000,
    article: "ИД-10",
    category: "женская",
  },
  {
    _id: 3,
    type: "3",
    name: "Волейбольная форма",
    image: ["/img/volleyball/complect-20.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 4,
    type: "3",
    name: "Волейбольная форма",
    image: ["/img/volleyball/complect-30.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 5,
    type: "3",
    name: "Волейбольная майка",
    image: ["/img/volleyball/tshirt-1.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
  {
    _id: 6,
    type: "3",
    name: "Волейбольная майка",
    image: ["/img/volleyball/tshirt-10.png"],
    price: 15000,
    article: "ИД-11",
    category: "мужская",
  },
];
